<?php

use Illuminate\Database\Seeder;

class MobiliariosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mobiliarios')->delete();

        DB::table('mobiliarios')->insert([
            ['mobiliario'=>'Escaparate 1'],
            ['mobiliario'=>'Escaparate2'],
            ['mobiliario'=>'Ray Ban Window Gogo 1'],
            ['mobiliario'=>'Ray Ban Window Gogo 2'],
            ['mobiliario'=>'Ray Ban Window Gogo 3'],
            ['mobiliario'=>'Small Exhibition Table RB'],
            ['mobiliario'=>'Accessory Tool (17/01/19no llegado aun)'],
            ['mobiliario'=>'Accessory Gogo'],
            ['mobiliario'=>'Accessory Integrated'],
            ['mobiliario'=>'Accessory Tool'],
            ['mobiliario'=>'Celebration Table'],
            ['mobiliario'=>'Celebration Table (B) 2'],
            ['mobiliario'=>'Celebration Table Multimedia Table 1'],
            ['mobiliario'=>'Celebration Table Multimedia Table 2'],
            ['mobiliario'=>'Celebration Table Small Exhibition Table'],
            ['mobiliario'=>'Celebration Table (A) 2'],
            ['mobiliario'=>'Celebration Table (C) 2'],
            ['mobiliario'=>'Celebration Table Córner pequeño 2'],
            ['mobiliario'=>'Celebration Table Multimedia Table'],
            ['mobiliario'=>'Celebration Table Multimedia Table Ray Ban'],
            ['mobiliario'=>'Celebration Table New Collection'],
            ['mobiliario'=>'Celebration Table New Collection Small Exhibition Table'],
            ['mobiliario'=>'Celebration Table New Collection Córner pequeño 4'],
            ['mobiliario'=>'Celebration Table New Collection Multimedia Table'],
            ['mobiliario'=>'City Wall'],
            ['mobiliario'=>'FD Focal Unit (1)'],
            ['mobiliario'=>'FD Focal Unit (2)'],
            ['mobiliario'=>'FD Focal Unit (3)'],
            ['mobiliario'=>'FD Focal Unit (4)'],
            ['mobiliario'=>'Gondola'],
            ['mobiliario'=>'Gondola (1)'],
            ['mobiliario'=>'Gondola (2)'],
            ['mobiliario'=>'Lightbox'],
            ['mobiliario'=>'Medida Escaparate 1'],
            ['mobiliario'=>'Medida Escaparate 2'],
            ['mobiliario'=>'Medida Escaparate 3'],
            ['mobiliario'=>'Medida Escaparate 4'],
            ['mobiliario'=>'New Collection Gogo'],
            ['mobiliario'=>'Oakley Special Furniture'],
            ['mobiliario'=>'Oakley Table - Small Exhibition Table'],
            ['mobiliario'=>'Polar Shelf 2.0'],
            ['mobiliario'=>'Promotional Table Big'],
            ['mobiliario'=>'Promotional Table Big (1)'],
            ['mobiliario'=>'Promotional Table Big (2)'],
            ['mobiliario'=>'Promotional Table Small'],
            ['mobiliario'=>'Ray Ban Column'],
            ['mobiliario'=>'Ray Ban Counter F1'],
            ['mobiliario'=>'Ray Ban Counter F2'],
            ['mobiliario'=>'Ray Ban Midfloor F1'],
            ['mobiliario'=>'Ray Ban Midfloor F2'],
            ['mobiliario'=>'Ray Ban Tower'],
            ['mobiliario'=>'Ray Ban Wall - W1'],
            ['mobiliario'=>'Ray Ban Wall - W1 (1)'],
            ['mobiliario'=>'Ray Ban Wall - W1 (2)'],
            ['mobiliario'=>'Ray Ban Wall - W1 SD'],
            ['mobiliario'=>'Ray Ban Wall - W1S'],
            ['mobiliario'=>'Ray Ban Wall - W2'],
            ['mobiliario'=>'Ray Ban Wall - W2 (1)'],
            ['mobiliario'=>'Ray Ban Wall - W2 (2)'],
            ['mobiliario'=>'Ray Ban Wall - W2 (3)'],
            ['mobiliario'=>'Ray Ban Wall - W2 (4)'],
            ['mobiliario'=>'Ray Ban Wall - W3'],
            ['mobiliario'=>'Ray Ban Wall - W3 (1)'],
            ['mobiliario'=>'Ray Ban Wall - W3 (2)'],
            ['mobiliario'=>'Ray Ban Wall - W3L'],
            ['mobiliario'=>'Ray Ban Wall - W4'],
            ['mobiliario'=>'Ray Ban Window Gogo'],
            ['mobiliario'=>'Ray Ban Window gogo F1'],
            ['mobiliario'=>'Ray Ban Window gogo F1 (1)'],
            ['mobiliario'=>'Ray Ban Window gogo F1 (2)'],
            ['mobiliario'=>'Ray Ban Window gogo F1 (3)'],
            ['mobiliario'=>'Ray Ban Window gogo F1 (4)'],
            ['mobiliario'=>'Ray Ban Window gogo F1 (5)'],
            ['mobiliario'=>'Ray Ban window gogo NEW'],
            ['mobiliario'=>'Small Exhibition Table New Collection'],
            ['mobiliario'=>'Smart Shopper Touch'],
            ['mobiliario'=>'Table BBA'],
            ['mobiliario'=>'Tela tensada'],
            ['mobiliario'=>'Theme gogo (gogo+podium)'],
            ['mobiliario'=>'Theme gogo (gogo+podium+gogo)'],
            ['mobiliario'=>'Theme gogo 1'],
            ['mobiliario'=>'Theme gogo 1 (1)'],
            ['mobiliario'=>'Theme gogo 1 (2)'],
            ['mobiliario'=>'Theme gogo 2 (A)'],
            ['mobiliario'=>'Theme gogo 2 (B)'],
            ['mobiliario'=>'Theme Gogo 3'],
            ['mobiliario'=>'Theme gogo 3 (A)'],
            ['mobiliario'=>'Theme gogo 3 (A) 1'],
            ['mobiliario'=>'Theme gogo 3 (A) 2'],
            ['mobiliario'=>'Theme gogo 3 (B)'],
            ['mobiliario'=>'Theme gogo 3 (B) 1'],
            ['mobiliario'=>'Theme gogo 3 (B) 2'],
            ['mobiliario'=>'Theme gogo 3 (C)'],
            ['mobiliario'=>'Theme gogo 3 (C) 1'],
            ['mobiliario'=>'Theme gogo 3 (C) 2'],
            ['mobiliario'=>'Theme gogo 3 Multimedia Table'],
            ['mobiliario'=>'Theme gogo 3 Multimedia Table 1'],
            ['mobiliario'=>'Theme gogo 3 Multimedia Table 2'],
            ['mobiliario'=>'Theme gogo 3 Multimedia Table Ray Ban'],
            ['mobiliario'=>'Theme gogo 3 Small Exhibition Table'],
            ['mobiliario'=>'Theme gogo RB - Multimedia Table'],
            ['mobiliario'=>'Totem'],
            ['mobiliario'=>'Wall'],
            ['mobiliario'=>'Wall Pigeonhole'],
            ['mobiliario'=>'Wall Pigeonhole 24"'],
            ['mobiliario'=>'Wall Pigeonhole 48"'],
            ['mobiliario'=>'Wall Unit 24"'],
            ['mobiliario'=>'Wall Unit 48"'],
            ['mobiliario'=>'Wall Unit 48" Mirror band'],
            ['mobiliario'=>'Wall Unit 48" See Through'],
            ['mobiliario'=>'Window'],
            ['mobiliario'=>'Window Banner'],
            ['mobiliario'=>'Window Banner RB'],
            ['mobiliario'=>'Window Gogo'],
            ['mobiliario'=>'Window Gogo (1)'],
            ['mobiliario'=>'Window Gogo (1) RB'],
            ['mobiliario'=>'Window Gogo (2)'],
            ['mobiliario'=>'Window Gogo (2) RB'],
            ['mobiliario'=>'Window Gogo (3)'],
            ['mobiliario'=>'Window Gogo (4)'],
            ['mobiliario'=>'Window Gogo 1'],
            ['mobiliario'=>'Window Gogo 1 (3.0)'],
            ['mobiliario'=>'Window Gogo 2'],
            ['mobiliario'=>'Window Gogo 2 (3.0)'],
            ['mobiliario'=>'Window Gogo 2.0'],
            ['mobiliario'=>'Window Gogo 2.0 (1)'],
            ['mobiliario'=>'Window Gogo 2.0 (2)'],
            ['mobiliario'=>'Window Gogo 2.0 (3)'],
            ['mobiliario'=>'Window Gogo 3'],
            ['mobiliario'=>'Window Gogo 3.0'],
            ['mobiliario'=>'Window Gogo 3.0 Ray Ban'],
            ['mobiliario'=>'Window Gogo 3.0 Ray Ban 1'],
            ['mobiliario'=>'Window Gogo 3.0 Ray Ban 2'],
            ['mobiliario'=>'Window Gogo Córner grande 1'],
            ['mobiliario'=>'Window Gogo Córner grande 3'],
            ['mobiliario'=>'Window Gogo Ray-Ban 2.0'],
            ['mobiliario'=>'Window Gogo RB'],
            ['mobiliario'=>'Window Gogo RB 1'],
            ['mobiliario'=>'Window Gogo RB 2'],
            ['mobiliario'=>'Window Gogo RB 3'],
            ['mobiliario'=>'Window Gogo RB 4'],
            ['mobiliario'=>'Window Gogo SGH'],
            ['mobiliario'=>'Window Ray-Ban'],
            ['mobiliario'=>'Window RB'],
            ['mobiliario'=>'Window SGH'],
            ]);
        }
    }